config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  devise_for :users
	root to: 'comments#themeindex'
    resources :blogs do
  resources :comments
end
get "/themeindex" => "comments#themeindex", :as => :themeindex
get "/themeimagelogo" => "comments#themeimagelogo", :as => :themeimagelogo
get "/topmainmenu" => "comments#topmainmenu", :as => :topmainmenu
get "/typography" => "comments#typography", :as => :typography
get "/templates" => "comments#templates", :as => :templates
get "/widgets" => "comments#widgets", :as => :widgets
get "/table" => "comments#table", :as => :table
get "/datatable" => "comments#datatable", :as => :datatable
get "/formelement" => "comments#formelement", :as => :formelement
get "/formcomponent" => "comments#formcomponent", :as => :formcomponent
get "/formexample" => "comments#formexample", :as => :formexample
get "/formvalidation" => "comments#formvalidation", :as => :formvalidation
get "/colors" => "comments#colors", :as => :colors
get "/animations" => "comments#animations", :as => :animations
get "/boxshadow" => "comments#boxshadow", :as => :boxshadow
get "/buttons" => "comments#buttons", :as => :buttons
get "/icons" => "comments#icons", :as => :icons
get "/alerts" => "comments#alerts", :as => :alerts
get "/preloaders" => "comments#preloaders", :as => :preloaders
get "/notificationdialog" => "comments#notificationdialog", :as => :notificationdialog
get "/media" => "comments#media", :as => :media
get "/components" => "comments#components", :as => :components
get "/othercomponents" => "comments#othercomponents", :as => :othercomponents
get "/breadcrumbdemo" => "comments#breadcrumbdemo", :as => :breadcrumbdemo
get "/flotcharts" => "comments#flotcharts", :as => :flotcharts
get "/othercharts" => "comments#othercharts", :as => :othercharts
get "/calendar" => "comments#calendar", :as => :calendar
get "/photos" => "comments#photos", :as => :photos
get "/phototimeline" => "comments#phototimeline", :as => :phototimeline
get "/profileabout" => "comments#profileabout", :as => :profileabout
get "/listview" => "comments#listview", :as => :listview
get "/messages" => "comments#messages", :as => :messages
get "/pricingtable" => "comments#pricingtable", :as => :pricingtable
get "/contacts" => "comments#contacts", :as => :contacts
get "/wall" => "comments#wall", :as => :wall
get "/invoice" => "comments#invoice", :as => :invoice
get "/login" => "comments#login", :as => :login
get "/lockscreen" => "comments#lockscreen", :as => :lockscreen
get "/e404" => "comments#e404", :as => :e404
get "/genericclasses" => "comments#genericclasses", :as => :genericclasses

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	belong_to:blog
	
end

app/models/blog.rb
class Blog < ApplicationRecord
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_many :attachments
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	def tag_list
  tags.join(", ")
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/tag.rb
class Tag < ApplicationRecord
has_many :taggings
has_many :blogs, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
	belongs_to :blog
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	
	def index
		@blogs=Blog.all
    end
   def show
   	@blog = Blog.find(params[:id])
    @comment = Comment.new
     @comment.blog_id = @blog.id
   end
   def new
   	@blog = Blog.new
   end
   def create
   	@blog = Blog.new(blog_params)
  @blog.save
  flash.notice = "Blog '#{@blog.title}' Created!"

  redirect_to blog_path(@blog)
   end
   def destroy
   	@blog = Blog.find(params[:id]).destroy
   	flash.notice = "Blog '#{@blog.title}' Destroyed!"
   	redirect_to blogs_path
   end
   def edit
  @blog = Blog.find(params[:id])
end
  def update
  @blog = Blog.find(params[:id])
  @blog.update(blog_params)
  flash.notice = "Blog title '#{@blog.title}' Updated!"

  redirect_to blog_path(@blog)
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
  @comment = Comment.new(comment_params)
  @comment.blog_id = params[:blog_id]

  @comment.save

  redirect_to blog_path(@comment.blog)
end
def comment_params
  params.require(:comment).permit(:author_name, :body)
end
def themeindex
  end
  def themeimagelogo
  end
  def topmainmenu
  end
  def typography
  end
  def templates
  end
  def widgets
  end
  def table
  end
  def datatable
  end
  def formcomponent
  end
  def formelement
  end
  def formvalidation
  end
  def formexample
  end
  def colors
  end
  def animations
  end
  def boxshadow
  end
  def buttons
  end
  def icons
  end
  def alerts
  end
  def preloaders
  end
  def notificationdialog 
  end
  def media
  end
  def components
  end
  def othercomponents
  end
  def breadcrumbdemo
  end
  def flotcharts
  end
  def othercharts
  end
  def calendar
  end
  def photos
  end
  def phototimeline
  end
  def profileabout
  end
  def listview
  end
  def messages
  end
  def pricingtable
  end
  def contacts
  end
  def wall
  end
  def invoice
  end
  def login
  end
  def lockscreen
  end
  def e404
  end
  def genericclasses
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper

  def blog_params
    params.require(:blog).permit(:title, :body, :image)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.blog.created_at, comment.created_at) %> later</p>
</div>

app/views/blogs/_form.html.erb
<%= form_for(@blog, html: {multipart: true}) do |f| %>

  <ul>
  <% @blog.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
  <% if @blog.image.exists? %>
      <%= image_tag @blog.image.url (:medium)%><br/>
  <% end %>
  <%= f.label :image, "Attach a New Image" %><br/>
  <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit an Blog</h1>
<%= render partial: 'form' %>

app/views/blogs/index.html.erb
<h1>All Blogs</h1>

<ul id="blogs">
  <% @blogs.each do |blog| %>
    <li>
      <%= link_to blog.title, blog_path(blog) %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a New Blog", new_blog_path, class: "new_article" %>

app/views/blogs/new.html.erb
<h1>Create a New Blog</h1>
<%= render partial: 'form' %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>
<p><%= @blog.body %></p>
<% if @blog.image.exists? %>
      <%= image_tag @blog.image.url (:medium)%><br/>
  <% end %>
<h3>Comments (<%= @blog.comments.size %>)</h3>
<%= render partial: 'blogs/comment', collection: @blog.comments %>
<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Blogs List", blogs_path %>
<%= link_to "delete", blog_path(@blog), method: :delete,data: {confirm: "Really delete the article?"}%>

<%= link_to "edit", edit_blog_path(@blog) %>

app/views/comments/lockscreen.html.erb
<style type="text/css">
    .abc {
       display: block;
    margin-left: auto;
    margin-right: auto ;
     top: 30%;                      
   transform: translate(0, -50%);
   }
</style>
<body class="login-content">
        <div class="lc-block lcb-alt toggled abc" id="l-lockscreen"> 
            
            <img class="lcb-user" src="/assets/img/profile-pics/profile-pic-2.jpg" alt="">
            
            <div class="fg-line">
                <input type="password" class="form-control text-center" placeholder="Password">
            </div>

            <a href="" class="btn btn-login btn-danger btn-float"><i class="zmdi zmdi-arrow-forward"></i></a>

            <ul class="login-navigation">
                <li data-block="#l-register" class="bgm-green" data-ng-click="lctrl.forgot = 0; lctrl.register = 1">Not Mallinda Hollaway?</li>
            </ul>
        </div>
        
        <!-- Older IE warning message -->
        <!--[if lt IE 9]>
            <div class="ie-warning">
                <h1 class="c-white">Warning!!</h1>
                <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
                <div class="iew-container">
                    <ul class="iew-download">
                        <li>
                            <a href="http://www.google.com/chrome/">
                                <img src="img/browsers/chrome.png" alt="">
                                <div>Chrome</div>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.mozilla.org/en-US/firefox/new/">
                                <img src="img/browsers/firefox.png" alt="">
                                <div>Firefox</div>
                            </a>
                        </li>
                        <li>
                            <a href="http://www.opera.com">
                                <img src="img/browsers/opera.png" alt="">
                                <div>Opera</div>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.apple.com/safari/">
                                <img src="img/browsers/safari.png" alt="">
                                <div>Safari</div>
                            </a>
                        </li>
                        <li>
                            <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                                <img src="img/browsers/ie.png" alt="">
                                <div>IE (New)</div>
                            </a>
                        </li>
                    </ul>
                </div>
                <p>Sorry for the inconvenience!</p>
            </div>   
        <![endif]-->
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
    <%= yield %>
     <%= javascript_include_tag 'zyield' %>
  </body>
</html>